### ISSUE TITLE
Skip Masking/cluster particular tokens

### ISSUE THREAD

**Issue by stanchion-bishoyi** [IBM/Drain3#45]
Example:
> sentence 1: "review 1 - [INFO] The syntax is right."
> sentence 2: "review 2 - [ERROR] The syntax is faulty."
--------------------------------------
Cluster formed: 
> "review <:NUM:> - <*> The syntax is <*>"
--------------------------------------
Expected cluster: 
> "review <:NUM:> - [INFO] The syntax is <*>", 
> "review <:NUM:> - [ERROR]The syntax is <*>".

How can I prevent masking/ clustering some particular tokens like here, in this case, I want to keep INFO/ERROR as it is in two different clusters. (not masked into <*>).

**Comment by davidohana** [comment]
This si not currently possible

**Comment by phamquiluan** [comment]
> This is not currently possible

Sorry for commenting on this old issue. But, I'm wondering why is that? and is there any way to overcome this?

Thank you so much @davidohana

**Comment by Superskyyy** [comment]
> > This is not currently possible
> 
> Sorry for commenting on this old issue. But, I'm wondering why is that? and is there any way to overcome this?
> 
> Thank you so much @davidohana

The reason is that the clustering mechnism is based on similiarty threshold, and as you can see here the similiarty is very high given the sequences. If you would like to overcome this, a simple way is to implement a specific rule to separate INFO and ERROR logging levels before the merge replace is done. or you can try to mask the logging levels with specifc MASKTOKENs then the similiarty will decrease given the masked tokens are different. Appoarch 1 is guaranteed to separate, while 2 will likely reduce a part of the problem.

**Comment by phamquiluan** [comment]
I see. Thank you so much @Superskyyy. The first solution to mask `[INFO]` to `<:INFO:>` seems legit. I will give it a try.
